# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  role:
    default: "consumer"
    description: Which role this app is expected to have.
    type: string
  topic_name:
    default: "test-topic"
    description: Name of the topic to be used.
    type: string
  replication_factor:
    default: 1
    description: Replication factor for the topic when created
    type: int
  consumer_group_prefix:
    description: Consumer group to be used by default
    type: string
  partitions:
    default: 5
    descriptions: Number of partitions for the topic when created
    type: int
  num_messages:
    default: 1000
    descriptions: Number of messages.
    type: int
