# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  roles:
    default: "consumer,producer"
    description: Which role this app is expected to have.
    type: string
  topic-name:
    default: "test-topic"
    description: Name of the topic to be used.
    type: string
  replication-factor:
    default: 3
    description: Name of the topic to be used.
    type: int
  consumer-group-prefix:
    description: Consumer group to be used by default
    type: string
  auto-start:
    default: true
    description: whether the process is started straight away or need manual triggering
    type: boolean

